language: java
before_install:
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r21.0.1-linux.tgz
  - tar -xzf android-sdk_r21.0.1-linux.tgz
  - export ANDROID_HOME=~/build/duckduckgo/android/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo PATH
  - echo ANDROID_HOME
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level
  # you are building for android (run "android list sdk" to get the full list. 9 = 2.3.3 or API level 10
  - android update sdk --filter platform-tools,android-16,extra-android-support,android-17,sysimg-17 --no-ui --force
  - android list targets
  - echo "sdk.dir=`pwd`/android-sdk-linux" > local.properties
  - echo "sdk.dir=`pwd`/android-sdk-linux" > ./libs/OnionKit/libonionkit/local.properties
  - # PROVISIONAL: changed SDKr22 build-tools path. create symbolic link
  - if [ ! -e ${ANDROID_HOME}/platform-tools/aapt ]; then ln -s ${ANDROID_HOME}/build-tools/$ANDROID_BUILD_TOOLS_VERSION/aapt ${ANDROID_HOME}/platform-tools/aapt; fi
  - if [ ! -e ${ANDROID_HOME}/platform-tools/aidl ]; then ln -s ${ANDROID_HOME}/build-tools/$ANDROID_BUILD_TOOLS_VERSION/aidl ${ANDROID_HOME}/platform-tools/aidl; fi
  - if [ ! -e ${ANDROID_HOME}/platform-tools/dx ]; then ln -s ${ANDROID_HOME}/build-tools/$ANDROID_BUILD_TOOLS_VERSION/dx ${ANDROID_HOME}/platform-tools/dx; fi
  - if [ ! -e ${ANDROID_HOME}/platform-tools/lib ]; then ln -sf ${ANDROID_HOME}/build-tools/$ANDROID_BUILD_TOOLS_VERSION/lib ${ANDROID_HOME}/platform-tools/lib; fi


before_script:  
  - android update project -p . --subprojects --target "android-17"
  - android update project -p ./libs/OnionKit/libonionkit/ --subprojects --target "android-17"
  - ant clean debug
