language: java
jdk: oraclejdk7
before_script:
    - sudo wget -q http://dl.google.com/android/android-sdk_r18-linux.tgz
    - sudo tar xzvf android-sdk_r18-linux.tgz > /dev/null
    - sudo android-sdk-linux/tools/android -s update sdk --filter android-7,platform-tool --no-ui
    - sudo android-sdk-linux/tools/android -s update project --path ./android --target "android-7"
    - sudo android-sdk-linux/tools/android -s update test-project --path ./android -m ../android
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

    # Install required Android components.
    # Note that the command below only accepts the first license. This is actually convenient, since
    # it prevents the installation of the ATOM and MIPS emulator images.
    - echo yes | android update sdk --filter platform-tools,build-tools-18.0.0,android-17,android-16,extra-android-support --no-ui --force